spring.application.name=authenticationService
server.port=8080
#postgresql://postgres:npg_ov30qlcdgNFu@ep-dark-union-a5fr2ne0-pooler.us-east-2.aws.neon.tech/jobsphere?sslmode=require
spring.datasource.url=jdbc:postgresql://ep-dark-union-a5fr2ne0-pooler.us-east-2.aws.neon.tech:5432/jobsphere?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=npg_ov30qlcdgNFu
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=mysecuresecretkeywhichislongenough1234567890soitneedsmorethan256bitsize
#1day(in millisecond)
jwt.expirationMS=86400000 

spring.cloud.config.import-check.enabled=false
